Spike Google Analytics 4 Only TurboLinks (Not CSP)
PEM-Humboldt/biomodelos-website pull request #343
Opened 2021-12-16 16:37 UTC by cazapatamar

2021-12-16 16:42 UTC, cazapatamar commented
Please check this implementation and let me know your opinions. CSP is skipped as apparently it is necessary to have SSL certificate.

I tested on GA website and it is created some traffic from my local environment by executing the application.

2021-12-16 20:50 UTC, erikasv commented
LGTM but Daniel is who should give the green light.

Also please add the new line at the end of `manifest.js` and  `analytics.js`

2021-12-17 02:00 UTC, cazapatamar commented
Deleted the analytics.js.coffee file and this implementation still works

2022-01-26 21:23 UTC, danflop commented
@cazapatamar I was checking out the traffic generated by the test and I only see information about the main page. We should test more visiting different sections and also different species using the search bar and also directly using a species URL.

GA4
![image.png](https://images.zenhubusercontent.com/5898844951aa2c3057739338/5a859dc3-daff-4626-83e6-d16028d87d23)

Production GA

![image.png](https://images.zenhubusercontent.com/5898844951aa2c3057739338/8bd3916d-ccd4-47f3-9801-912e51d53db7)

2022-01-31 13:16 UTC, danflop commented on app/views/layouts/application.html.erb
> +            <script async src="https://www.googletagmanager.com/gtag/js?id=G-WD07J9FEXQ"></script>
Please check indentation of this section.

2022-01-31 13:17 UTC, danflop requested changes
Check indentation of the changes.

2022-01-31 16:21 UTC, cazapatamar commented
> 

@danflop Done. Check again please.

2022-01-31 21:46 UTC, danflop approved these changes

2022-02-01 03:00 UTC, merged