Update statistic models message
PEM-Humboldt/biomodelos-website pull request #399
Opened 2023-08-31 23:15 UTC by cazapatamar

2023-08-31 23:54 UTC, erikasv requested changes
undo the changes and disable the format on save for the yml files.

I you want to update that format do it in a separated commit

2023-09-01 01:20 UTC, cazapatamar commented
> undo the changes and disable the format on save for the yml files.
> 
> I you want to update that format do it in a separated commit

Done!

2023-09-01 01:25 UTC, cazapatamar commented
@erikasv For testing purposes, you can use taxID = 932 in the test database.

2023-09-01 17:45 UTC, erikasv approved these changes

2023-09-01 17:51 UTC, merged