Feature/recaptcha v3 keeping v2
PEM-Humboldt/biomodelos-website pull request #457
Opened 2024-08-02 17:02 UTC by cazapatamar

## 🛠️ Changes
- reCAPTCHA v2 and v3 simultaneously in the signup and contact forms

## 📝 Associated issues
#424 

## 🤔 Considerations
Obtain the keys from the Google reCAPTCHA website for now. When GitLab becomes available, I will update the new environment variable names and values there.

2024-08-08 15:52 UTC, erikasv commented on app/controllers/registrations_controller.rb
> +		  recaptcha_v2_valid = verify_recaptcha unless recaptcha_v3_valid
wring indentation

2024-08-12 14:25 UTC, erikasv requested changes
lgtm just some small adjustments

2024-08-12 14:25 UTC, erikasv commented on app/controllers/home_controller.rb
> +
remove these lines

2024-08-12 14:25 UTC, erikasv commented on app/controllers/registrations_controller.rb
> +  	prepend_before_action :check_captcha, only: [:create]
fix indentation

2024-08-12 17:07 UTC, ManuelStardust approved these changes

2024-08-12 18:37 UTC, merged